### ISSUE TITLE
[Question] What is system working set and how to increase it?

### ISSUE THREAD

**Issue by TheDGOfficial** [henrypp/memreduct#100]
I know what is physical memory and virtual memory but don't know what is system working set. And my physical memory and virtual memory is fine, but system working set goes up to %80 and %90, and that causes a slowdown until I click "Clean Memory". I have set auto clear on %90 but it does not clear it automatically. And this system working set thing has small memory. How can I increase it?

![image](https://user-images.githubusercontent.com/24778409/106808474-7a12e000-667b-11eb-8a1a-748164d68bc5.png)

Like above, it says only 14,8 MB can be used and 105 MB is empty.

Also, I don't have an SSD and my disk is not a fast one. So I want to avoid using virtual memory when physical memory is available, but Windows uses it anyway, when there are physical RAM. Is it using for low priority things? Can it cause slowdown?

**Comment by henrypp** [comment]
> And my physical memory and virtual memory is fine, but system working set goes up to %80 and %90, and that causes a slowdown
> And this system working set thing has small memory. How can I increase it?

You do not need do anything with System Working Set, this is cache for Windows purpose, and if your computer move slowly, System Working Set is the last reason for that.
