### ISSUE TITLE
System working set warning on startup

### ISSUE THREAD

**Issue by palashman** [henrypp/memreduct#102]
Hi,
every time I start my PC, I see the following warning (see screenshot)
![image](https://user-images.githubusercontent.com/44644036/108174315-55554880-7110-11eb-8081-65f7ae33ea69.png)

I have 8G RAM and 4G swap. It started after I turn on swap. And before (with no swap) all were ok.

Thanks.

**Comment by TheDGOfficial** [comment]
I have a similar problem on #100 , don’t know what it is.
