### ISSUE TITLE
its truth that Memreduct kills RAM? or its fake info?

### ISSUE THREAD

**Issue by nikita-tarasov3** [henrypp/memreduct#104]
its truth that Memreduct kills RAM? or its fake info?
I'm confused. I read some comments from other site and people say: blue windows screen, ram rip and etc.

**Comment by eric15342335** [comment]
> its truth that Memreduct kills RAM? or its fake info?
of course.
why you'll have that kind of information dude?

**Comment by nikita-tarasov3** [comment]
> > its truth that Memreduct kills RAM? or its fake info?
> 
> of course.
> why you'll have that kind of information dude?

Idk

**Comment by GFOXSH** [comment]
> Idk
Проблема наблюдалась у меня, но была связана не с MemReduct, а с недостатоком питания ЦП после андервольта. Программой пользуюсь постоянно практически с первого дня знакомства, еще ни разу не подводила.
