### ISSUE TITLE
Modified page list and Standby list isn't automatically being cleaned

### ISSUE THREAD

**Issue by OlimDev** [henrypp/memreduct#106]
Modified page list isn't automatically being cleaned. And also cleans the memory much efficiently, also you don't have to worry about mem reduct automatically cleans the modified page list and not responding after that.

**Comment by OlimDev** [comment]
The standby list needs to be removed, clearing it will not add any benefit.

**Comment by Chilace** [comment]
> The standby list needs to be removed, clearing it will not add any benefit. Its causing more problems than good.

Proof ?

**Comment by OlimDev** [comment]
For low end users, removing or clearing the standby list will slow down applications like Chrome, Opera, and other browsers that I don't know exist.

**Comment by OlimDev** [comment]
It will add benefits like more FPS and that's it.

**Comment by OlimDev** [comment]
Hence, that's why standby list exist.

**Comment by OlimDev** [comment]
Will this problem will be fixed or it is a feature.

**Comment by OlimDev** [comment]
Oops...

**Comment by OlimDev** [comment]
I just found out that you can just use the older version.
