### ISSUE TITLE
100% Usage System working set

### ISSUE THREAD

**Issue by FreeHitss** [henrypp/memreduct#108]
System working Set 

Usage 100% whenever i play game or on start up

How to fix? please help my games are crashing
![Untitled](https://user-images.githubusercontent.com/20654631/119218065-e1607d00-bb10-11eb-8270-3e88c52ed1c5.png)

**Comment by henrypp** [comment]
> Usage 100% whenever i play game or on start up

So what?

> please help my games are crashing
Games crashing not because of System Working Set.

**Comment by Hipol1to** [comment]
i got the same problem, have you guys more information?
