### ISSUE TITLE
Clicking on the "clean memory" button does different actions than the hotkeys or auto cleaner

### ISSUE THREAD

**Issue by gabethecoder123** [henrypp/memreduct#109]
Hello Henry,

Hope you are having a great day!

I am testing some memory exhaustion here and then using your APP for cleanup (which is the best found out there, congrats), but the actions for the "clean memory" button are different than hot keys or the auto cleaner. I guess they are not checking the settings of memory regions.

Can you please address that? I'll provide some funds when done! Thanks

**Comment by henrypp** [comment]
Here is explanation #92 and option is added, just wait for next reelase.
