### ISSUE TITLE
How-to Silent Install

### ISSUE THREAD

**Issue by Jadereberlly** [henrypp/memreduct#114]
Can you send Instructs Setup to silent or very silent install ?

**Comment by henrypp** [comment]
https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers%3F

**Comment by Jadereberlly** [comment]
Did not work!
I tried to perform the silent installation in both ways,

1.  .\memreduct-3.3.5-setup.exe /s
2.  .\memreduct-3.3.5-setup.exe  /s /D=c:\Apps\memreduct

 all loads the setup screen
https://prnt.sc/1urt931
https://prnt.sc/1urtd2f

**Comment by henrypp** [comment]
> The above command line options are all case-sensitive, so /S will work, but /s won't. If you need them to work in a case-insensitive matter you have to provide some glue code in .onInit such as this one for "silent" functionality:
