### ISSUE TITLE
good to clean while gaming?

### ISSUE THREAD

**Issue by Wizardo777** [henrypp/memreduct#116]
it was very useful previously with my 3GB ram laptop but now I am using it in a modern gaming laptop 2021 
so if I clean memory while playing the high-end games will it cause any system failure or data to corrupt?

**Comment by FooqX** [comment]
Do you even know what memory means and how it works? If not, check wikipedia

**Comment by mhtvsSFrpHdE** [comment]
> it was very useful previously with my 3GB ram laptop but now I am using it in a modern gaming laptop 2021 so if I clean memory while playing the high-end games will it cause any system failure or data to corrupt?

@Wizardo777 Hi, I have some information that can prove  
clear standby list(*) before start game is good for reduce loading time:  https://github.com/henrypp/memreduct/issues/146

**Comment by henrypp** [comment]
Any problem is maded when you clean memory?
