### ISSUE TITLE
will black mode be possible?

### ISSUE THREAD

**Issue by Randmaster123** [henrypp/memreduct#118]
Hello, @henrypp are you thinking in add a black mode option?
This tool is useful but without the black mode is some bad for my eyes.

**Comment by henrypp** [comment]
black mode?

**Comment by Randmaster123** [comment]
> black mode?

Yes!

**Comment by ShivashishY** [comment]
> black mode?

he is asking can you add dark mode and light mode switchable theme like most android support now?

**Comment by mcflly** [comment]
That dark mode would be awsome and easier for my eyes. Can't wait for this update :))))

**Comment by henrypp** [comment]
I can't wait too, but [MICRO$OFT](https://github.com/microsoft) is still can't add this feature for win32 apps, only for UWP bullshit.
