### ISSUE TITLE
Cannot update to version 9:47 pm on January 11, 2020

### ISSUE THREAD

**Issue by SureFire2** [henrypp/memreduct#120]
It always reminds me to update to the latest version, but every time I update, I will be prompted that the connection to the server fails. The update fails

**Comment by henrypp** [comment]
winxp? vista? or other unsupported by websites shit?

**Comment by henrypp** [comment]
winxp/vista/7 - does not support tls 1.3 at all, which is used in github.com and henrypp.org websites.

**Comment by SureFire2** [comment]
> 眨眼？前景？还是其他不受网站支持的网站狗屎？

I don’t know what you mean, but I can’t update it. The version I’m using now is: v3.3.5

**Comment by SureFire2** [comment]
> winxp? vista? or other unsupported by websites shit?

I don’t know what you mean, but I can’t update it. The version I’m using now is: v3.3.5

**Comment by henrypp** [comment]
> I don’t know what you mean, but I can’t update it.

I mean if you working under winxp/vista/7 you cannot download updates in most of cases.

**Comment by SureFire2** [comment]
> > I don’t know what you mean, but I can’t update it.
> 
> I mean if you working under winxp/vista/7 you cannot download update in most of cases.

I use windows 11 system. Even if I start VPN in the background and connect to the United States, I can't update it

**Comment by henrypp** [comment]
> Even if I start VPN in the background and connect to the United States, I can't update it

You from china or what? Why VPN?

**Comment by SureFire2** [comment]
> > Even if I start VPN in the background and connect to the United States, I can't update it
> 
> You from china or what? Why VPN?

I am from China. I know there is a wall, but even if I activate the VPN, it cannot be updated. Why not put the new update file on GitHub?

**Comment by win98se** [comment]
If it's language file, you can download the latest one on https://github.com/henrypp/memreduct/raw/master/bin/memreduct.lng and replace the same existing file in your install directory.

**Comment by SureFire2** [comment]
> If it's language file, you can download the latest one on https://github.com/henrypp/memreduct/raw/master/bin/memreduct.lng and replace the same existing file in your install directory.

![1](https://user-images.githubusercontent.com/33777179/148162888-7e490e18-8e87-418a-98ee-4df766fcd698.png)
![2](https://user-images.githubusercontent.com/33777179/148162892-0d9c3fb4-2577-41a3-90d7-d51ed60c9fad.png)
![3](https://user-images.githubusercontent.com/33777179/148162895-a275d29e-4e18-4a83-9eaa-961c5be2103b.png)

**Comment by win98se** [comment]
The updater already states that this is only language pack update. Only the file `memreduct.lng` is changed.
Latest version of binary is still 3.3.5, **compiled and published in 2019**.

**Comment by SureFire2** [comment]
> The updater already states that this is only language pack update. Only the file is changed. Latest version of binary is still 3.3.5, **compiled and published in 2019**.`memreduct.lng`
> 
> **Just do the instructions [here](https://github.com/henrypp/memreduct/issues/120#issuecomment-1004910430), and the updater shall not annoy you again (unless there are further updates since).**

Okay, thank you
