### ISSUE TITLE
Possibility to use in CLI / hidden mode to use in scripts or scheduled tasks

### ISSUE THREAD

**Issue by IMNOTAA** [henrypp/memreduct#122]
Hey,

Title seems self explanatory, I'd like to use memreduct in a scheduled task that runs at startup, however since the tool is GUI only as far as I know it's not really possible.

I'm not a big fan of leaving memreduct running and have it clean every X amount of time, I feel like that could cause problems and hangups and so far I've gotten the result I wanted by just launching it once at startup, it stops the useless crap I don't need from hogging memory, and the stuff that eventually restarts is stuff that I do need.

So yeah basically is there any way to do what I want, and if not, is that planned in the future to add such functionnality ?

Thanks

**Comment by henrypp** [comment]
#82

**Comment by IMNOTAA** [comment]
Sorry man, don't know if I'm dumb or if there was some bug but I did check the previous issues to not be that guy, and I was that guy anyways because I didn't see it 😅
