### ISSUE TITLE
Есть две проблемы в Mem Reduct

### ISSUE THREAD

**Issue by Buddha000** [henrypp/memreduct#123]
Здравствуйте! У меня с Mem Reduct две проблемы:
1. Перестала работать очистка памяти по заполнении. Работает только очистка по таймеру. Сначала я пользовался портативной версией; потом, из-за этой проблемы перешел на инсталлированную. Ситуация не изменилась.
2. Файл подкачки у меня отключен. Файл pagefile.sys отсутствует. Однако, программа показывает данные для какой-то виртуальной памяти. О какой виртуальной памяти идет речь?
У меня стоит Windows 7 Home Edition. Надеюсь на помощь. С уважением, Buddha000.

**Comment by henrypp** [comment]
1. Значит так настроили.
2. https://ru.wikipedia.org/wiki/Виртуальная_память
