### ISSUE TITLE
A small question about version 3.4

### ISSUE THREAD

**Issue by Ball727** [henrypp/memreduct#130]
Hello developers, after I updated the software (version 3.35) to 3.4, I found that the software will not start with the computer when I check the startup option in the settings next time it restarts or starts up. No matter if I use other methods to set it as a startup item, it will not take effect, so I am here to give feedback. In addition, when I use version 3.35, this software can be started normally. It would be great if you could find time to fix it! The software itself is really easy to use and convenient, thank you!

**Comment by muyou233** [comment]
Me too, setting it to auto-start at boot doesn't work.

**Comment by angel695555555** [comment]
still not working.. 3.4
what i tried
1. adding shortcut to shell:Startup not working too
2. run as admin 
3. startup does showing memreduct is enabled for startup

**Comment by Ball727** [comment]
> 我也是，设置为开机自启动不行。

Is your operating system win11 or win10?

**Comment by Ball727** [comment]
> 仍然无法正常工作.. 3.4 我尝试了什么
> 
> 1. 向 shell 添加快捷方式：启动也不起作用
> 2. 以管理员身份运行
> 3. 启动确实显示 memreduct 已启用启动

Is your operating system win11 or win10?

**Comment by Ball727** [comment]
I recently tried the 3.4 version of this software on win10, and found that it can be started normally when the computer is turned on. Before that, it was impossible to do it on the win11 system, which is very strange.

**Comment by Luro223** [comment]
Well Win11 is like the whole new os with new issues
This is why Win11 is such a waste of microsoft

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1141#issuecomment-1044264827
