### ISSUE TITLE
Вопрос по части api.

### ISSUE THREAD

**Issue by Llmon4ik** [henrypp/memreduct#133]
Привет, спасибо за столь полезное приложение. Я обладатель слабо-среднего пк. Когда игра забирает большую часть памяти у меня возникают проблемы с разворачиванием, и я не могу посмотреть очистилась ли у меня память, и сколько вообще очистилось. Я хотел бы реализовать приложение которое отправляло бы мне на телефон результат о чистке программой.
Могу ли я получать эту информацию простым способом, и если да то как?

**Comment by henrypp** [comment]
Как насчёт включить лог в файл?

**Comment by Llmon4ik** [comment]
Поподробнее пожалуйста

**Comment by henrypp** [comment]
Настройки, Дополнительно, Включить лог
