### ISSUE TITLE
Please create a separate "Check for Updates" for language packs

### ISSUE THREAD

**Issue by KirkH420** [henrypp/memreduct#135]
People who only speak English do not need to download extra language packs but they might like to be able to be notified about updates to the program code.

The way the app is currently setup, if I choose not to download your latest language pack update, I will be continually notified about it. There seems to be no way that I can prevent this notification unless I either download the language pack (which I don't want to do because I'm building an archive of portable apps that I will unpack on other windows installs and am trying to keep it small), or I can uncheck "occasionally check for updates" but then I'll have to check for updates manually.

Thank you.

**Comment by henrypp** [comment]
You can enable auto-download and auto install language packs if you want.
