### ISSUE TITLE
does not start at system startup

### ISSUE THREAD

**Issue by imadraude** [henrypp/memreduct#136]
MemReduct does not start at system startup, even though the corresponding option in the settings is checked

**Comment by imadraude** [comment]
![image](https://user-images.githubusercontent.com/59265133/157260435-b11aad24-b6a6-41e6-b267-308c916f161b.png)

**Comment by TcDhlPro** [comment]
**希望大佬可以修复一下** @henrypp

**Comment by TangTank** [comment]
you can try this:

run with administrator privileges

**Comment by TcDhlPro** [comment]
@TangTank 
It doesn't work, and many people have this problem

**Comment by Gorkido** [comment]
Disable UAC.

**Comment by opus-x** [comment]
@Gorkido What a awful suggestion. Use Windows' Task Manager.

**Comment by henrypp** [comment]
You login under another user, that administrator.

**Comment by TcDhlPro** [comment]
> Did anyone find a working way to start at startup?

[v.3.3.3](https://github.com/henrypp/memreduct/releases/tag/v.3.3.3)

**Comment by SAGEof6iixPATHS** [comment]
> > Did anyone find a working way to start at startup?
> 
> [v.3.3.3](https://github.com/henrypp/memreduct/releases/tag/v.3.3.3)

You saying I should downgrade?

**Comment by TcDhlPro** [comment]
> > > Did anyone find a working way to start at startup?
> > 
> > 
> > [v.3.3.3](https://github.com/henrypp/memreduct/releases/tag/v.3.3.3)
> 
> You saying I should downgrade?

Yes, only in V3.3.3, the auto start will be normal

**Comment by imadraude** [comment]
> Did anyone find a working way to start at startup?

just install portable version
