### ISSUE TITLE
FONT WON'T CHANGE

### ISSUE THREAD

**Issue by BoisdArc** [henrypp/memreduct#14]
I'm old with poor vision. I cannot make the font change so I can read it. I've changed it over-and-over, but it not hold. I would certainly appreciate some assistance.

**Comment by henrypp** [comment]
There cannot abbility to change UI font, but you can change font family, font size and font weight for tray icon in "Appearance" settings.

If you could change UI text and controls size - you can configure DPI size in Windows, Mem Reduct has support UI scale.

https://technet.microsoft.com/en-us/magazine/ff629368.aspx
