### ISSUE TITLE
Some problems in software

### ISSUE THREAD

**Issue by WangHuimin520** [henrypp/memreduct#141]
Dear author, there seems to be a bit of error in this software. The details are as follows: after installing the software, there are errors in the mouse click, double click and middle button. For example, I set Click to open the software and double-click to clean up. I found that click did not open the software, but cleaned up the memory as double-click。 Is there a solution? Thank you for reading, thank you
Windows11 x64 version

**Comment by squid233** [comment]
Same problem.

**Comment by henrypp** [comment]
@crzsotona bravo!
