### ISSUE TITLE
I want to clean processes working set only

### ISSUE THREAD

**Issue by sfanking** [henrypp/memreduct#150]
Thank you for your excellent software, it helped me a lot. I have found a problem in using it. working set option cleans up both processes working set and system working set, which is not what I want. Is it possible to list the processes working set separately or replace the working set cleanup option with it? Thanks! There is another software called WinMemoryCleaner on github which is simple but has this option for your reference.

**Comment by crzsotona** [comment]
Have you checked application options before opening issue?
![image](https://user-images.githubusercontent.com/13541485/190234891-1ee93689-5ff5-4151-aa63-24bfbf49fb87.png)
