### ISSUE TITLE
No se abre al iniciar windows

### ISSUE THREAD

**Issue by JLex11** [henrypp/memreduct#157]
It does not open when starting windows, although I have administrator permissions and the corresponding option is active.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/93395794/176675134-6ab6b707-44da-4a15-ad58-3b9c3ec70dcf.png">

**Comment by angel695555555** [comment]
same 3.4

**Comment by Big-Cake-jpg** [comment]
I don't have this problem.

Windows 11 Insider Preview Build 25215 (Dev Channel), Mem Reduct 3.4

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1141#issuecomment-1044264827
