### ISSUE TITLE
玩DNF时开启软件会导致键盘和鼠标间接性失灵，怎么解决？？

### ISSUE THREAD

**Issue by YanMingUP** [henrypp/memreduct#159]
玩DNF时开启软件会导致键盘和鼠标间接性失灵，怎么解决？？

**Comment by Big-Cake-jpg** [comment]
作者不是中国人，你就不能用英文开Issue？

**Comment by YanMingUP** [comment]
> 
真尼玛搞笑  你不是国外人玩什么gtihub呀？？？    谁规定不能用中文提问题了？  装什么大尾巴狼

**Comment by YanMingUP** [comment]
> 作者不是中国人，你就不能用英文开Issue？

真尼玛搞笑 你不是国外人玩什么gtihub呀？？？ 谁规定不能用中文提问题了？ 装什么大尾巴狼

**Comment by Big-Cake-jpg** [comment]
> > 作者不是中国人，你就不能用英文开Issue？
> 
> 
> 
> 真尼玛搞笑 你不是国外人玩什么gtihub呀？？？ 谁规定不能用中文提问题了？ 装什么大尾巴狼

那你觉得你用中文开issue人家能看懂🐎

**Comment by YanMingUP** [comment]
> > > 作者不是中国人，你就不能用英文开Issue？
> > 
> > 
> > 真尼玛搞笑 你不是国外人玩什么gtihub呀？？？ 谁规定不能用中文提问题了？ 装什么大尾巴狼
> 
> 那你觉得你用中文开issue人家能看懂🐎
> 
> gh本来就是国际性的平台，提issue都是尽量用英语的
你不知道有种软件叫翻译软件吗？？？   好好说话就完了

**Comment by h3yb** [comment]
> 

什么啥乱
