### ISSUE TITLE
Russian localisation fix suggestion

### ISSUE THREAD

**Issue by Vic2077** [henrypp/memreduct#16]
Sorry, i'm new here, so i'm not sure if i'm posting my suggestion in the reight place, but i haven't found a more appropriate place to post it, so i'll post it here. Correct me if i'm doing it wrong.

So, my suggestion, is to change "сохранено" in the baloon that pops up after memory cleaning to "освобождено" or "очищено". I don't know about other users, but to me it looks kinda wierd, since "сохранено" rather means "saved" in Russian. Like, in case of "Save our souls!" or "A fireman saved a woman from a burning building." or, in the best case "to save (download) a file to a hard disk", "to save game (status)" (in PC gaming), "to save changes (in a document)" - i.e. - to make something safe. While "освобождено" means "freed up" (in our case - extra MBs of RAM are freed from unneeded files and ready for use again, to store something new and relevant) and "очищено" means "cleaned" ("X MB of RAM were cleaned from unneeded junk")

**Comment by Phoenix1747** [comment]
You can edit the Russian translation file here: https://github.com/henrypp/memreduct/edit/master/bin/i18n/Russian.ini then, after you changed some parts, you save it and open this page https://github.com/henrypp/memreduct/compare . 
There you click on "compare across forks", choose your fork and write an appropriate description about the changes.
Finally you click on "create pull request" and then wait for henry to pull in your changes and you're done :D

**Comment by Vic2077** [comment]
Oh, thank you... Sounds a bit complicated for a newbie, but i'll guess it easier than it looks... ) I guess i'll give it a try later then...

**Comment by henrypp** [comment]
Сделано.
