### ISSUE TITLE
Mem Reduct no longer starts at system startup

### ISSUE THREAD

**Issue by Pavel8694** [henrypp/memreduct#161]
Greetings to all! I tried reinstalling the program, but it still does not start with Windows 10, although this option is enabled in the Mem Reduct settings and Task Manager. I really hope for your help.

**Comment by klyfkvk** [comment]
I have a way to solve this problem. You need to write the startup information of the mem reduct into HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run.
Then restart it

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1141#issuecomment-1044264827
