### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sami-soft** [henrypp/memreduct#164]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

windows 10 21h2

### Steps to reproduce

Unfortunately, the automatic update option is not disabled. When I disable it and close the program and run it again, the automatic update option is enabled again.

![2022-10-02_051655](https://user-images.githubusercontent.com/37217976/193453504-4283015c-75d4-4889-a966-e1f0fce2cf94.jpg)

### Actual behavior

Unfortunately, the automatic update option is not disabled. When I disable it and close the program and run it again, the automatic update option is enabled again.

**Comment by henrypp** [comment]
Can't reproduce. Check if memreduct.ini is not readonly.

**Comment by sami-soft** [comment]
> Can't reproduce. Check if memreduct.ini is not readonly.

I did not find the file "memreduct.ini"

There is no such file in the installed location

![Uploading 2022-10-03_154441.jpg…]()

**Comment by sami-soft** [comment]
> Can't reproduce. Check if memreduct.ini is not readonly.

I did not find the file "memreduct.ini"

There is no such file in the installed location

![00](https://user-images.githubusercontent.com/37217976/193576375-bcc5c421-8b9d-4efa-8cc5-6adaa7b7a866.jpg)

**Comment by sami-soft** [comment]
I changed the permission of the installed folder of the program to eveyone, the problem was solved and the file was created.
