### ISSUE TITLE
virtual memory

### ISSUE THREAD

**Issue by CoucouEureka** [henrypp/memreduct#168]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

When cleaning up memory, can you also clean up virtual memory?

### Suggested solution

clean  virtual memory

**Comment by henrypp** [comment]
It is already added.
