### ISSUE TITLE
Great System freeze during memory cleaning if all Memory Regions are selected.

### ISSUE THREAD

**Issue by Vic2077** [henrypp/memreduct#17]
If i select all available memory regions in the settings, after i iniciate memory clean my system freezes for almost a minute or so, and then stutter and lag like hell for some time. is it intended, or is it a bug? If it's intended, then i suggest adding a warning in the description of, or on checking the last two Regions ("Standby List (Vista and later)" and "Modified page list (Vista and later)") like "can/will cause the System to lag during cleaning", since the testing revealed that the problem only happens if those two options are checked.
Just in case it matters - the I'm using Win7 Ultimate x64 with 4 Gb RAM and the latest version of Mem Reduct (the previous version also had this problem).

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Hi, I also had similar results with hdd and amd processor, but with an ssd and intel only the Modified page list (last in clean areas) option freezes the system noticably. On this second system I run cleaning in every 15 minutes automatically without that last option and I never notice that it is running. I would also suggest mentioning some average time/showing process percentage/showing remaining time or something like that. :)

**Comment by henrypp** [comment]
3.3 Added warning message.
