### ISSUE TITLE
[Bug] Taskbar wont Autohide after Cleanmem

### ISSUE THREAD

**Issue by DerpcatMusic** [henrypp/memreduct#171]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

11

### Steps to reproduce

Clean memory with Memreduct

### Expected behavior

Memory cleans and taskbar should be working fine 

### Actual behavior

Taskbar will not autohide and now is on top of every app

**Comment by kml0798** [comment]
mine works fine also on windows11. I think thats a problem that most people will never be able to reproduce the bug. Maybe because you modified some settings that closed by defaut

**Comment by henrypp** [comment]
It is not  a declared feature.
