### ISSUE TITLE
Viraual Memory Can't clean up

### ISSUE THREAD

**Issue by HKMV** [henrypp/memreduct#174]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

win11 25262.1000

### Steps to reproduce

one: 1. Open the main interface 2. Click the cleanup button 3. The virtual memory has not decreased
two: Regular and more than 80% automatic cleaning, virtual memory has not decreased

### Expected behavior

virtual memory has decreased

### Actual behavior

virtual memory has not decreased

### Logs

[memreduct_debug.log](https://github.com/henrypp/memreduct/files/10225220/memreduct_debug.log)

**Comment by henrypp** [comment]
Virtual memory is not really cleaning up.

**Comment by HKMV** [comment]
> Virtual memory is not really cleaning up.

How do I clean up virtual memory?
