### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by imagination2357** [henrypp/memreduct#175]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

Sound can't be disabled for the app

### Suggested solution

Love this tool. I've set it up to clear the memory automatically. It makes a ding every time it does it however. How about adding an option to disable the sound?

**Comment by henrypp** [comment]
You can uncheck "enable notification sound" option in configuration, thats all.
