### ISSUE TITLE
[Feature] Can you provide a "Speedball" button window?

### ISSUE THREAD

**Issue by amqius** [henrypp/memreduct#177]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

When I use Wise care 365, it provides a button called Floting Window that exists on the screen in the style of a round button with the memory usage in the middle, and when I tap on it, it optimizes the memory. This button can be set to be placed at the top of the screen or not. Usually it is automatically hidden at the edge of the screen. 

### Suggested solution

Is it possible to have an option like this? Option to show in the taskbar tray or a "Speedball" button like Wise care 365? Because the one in the taskbar tray is sometimes collapsed.It can be in the style of a large square, which shows the percentage of memory usage. It is like an enlarged version of the tray icon, or similar to a mini version of the main interface.

**Comment by javascripet** [comment]
Jesus why there's someone will want that kind of grabage floating on the screen.

unreasonable

**Comment by amqius** [comment]
> Jesus why there's someone will want that kind of grabage floating on the screen.
> 
> unreasonable

Imagine that some program you use is full-screen and obscures the taskbar.
