### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by StewVed** [henrypp/memreduct#18]
Windows (10 32-bit) Defender finds what it thinks is a Trojan in MemReduct.

I imagine this is a false-positive, and hopefully you can find the cause and recode :)

**Comment by Phoenix1747** [comment]
It's the fault of the antivirus software. There is no need to recode, it's just all false-positives.
Also almost none of the av programs think it's a virus: https://virustotal.com/de/file/70216d6095f6869bb32bf32e8ad363e8ca351892f2ceab4b536fd7b93cb8edcd/analysis/1478174620/

Btw, you shouldn't be using Windows Defender ;)

**Comment by StewVed** [comment]
Heh, yup I just installed the old trusty Avast! and low and behold no threats detected... dodgy Windows Defender!

Great link m8, cheers!
