### ISSUE TITLE
[Feature] Build instructions

### ISSUE THREAD

**Issue by Anton-V-K** [henrypp/memreduct#185]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

I tried to build the project with VS2022 (on Windows) and faced compile-time errors:
```
1>c1 : fatal  error C1083: Cannot open source file: '..\routine\src\rapp.c': No such file or directory
1>c1 : fatal  error C1083: Cannot open source file: '..\routine\src\routine.c': No such file or directory
1>...\memreduct\src\main.c(4,1): fatal  error C1083: Cannot open include file: 'routine.h': No such file or directory
```
These are easy to resolve - an extra module https://github.com/henrypp/routine is needed (BTW why it isn't included as a submodule?)
This issue was reported multiple times in the past: #5, #13, #55, #72, #117.

### Suggested solution

README.md should contain minimal build instruction.
Ideally the project should be built with one click (clone, update submodules, open solution and build).
The instruction may also cover non-standard warnings like this one
```
[WARNING!] Compile-time warning: IDS_UPDATE_AUTOINSTALL ("D:\\...\\routine\\src\\rapp.c":3048)
```
Is it normal to have this one? Can it be resolved? Let it alone?

It also makes sense to specify minimum supported/recommended version of VS2022 as 17.4.x (it is the version when [ARM-support was made officially available](https://devblogs.microsoft.com/visualstudio/arm64-visual-studio-is-officially-here/)).
Just for the reference: opening the project in an older version (like 17.3.4) results in missing project properties:
![image](https://user-images.githubusercontent.com/20116984/233640515-64461d18-6bba-4f4c-ae7d-b0b0b7b8584d.png)
However the project can be build fine for x64 and Win32 in an older version of VS2022.
Probably it is a known issue in VS2022, which won't be fixed :)

**Comment by henrypp** [comment]
I think it is not needed.

and [routine is already exists in submodules](https://github.com/henrypp/memreduct/blob/master/.gitmodules), nad i think people who know basic git instruction will know what will need.

**Comment by Anton-V-K** [comment]
Well, though `.gitmodules` does exist, a straightforward attempt to update submodules with git (TortoiseGit) results in errors:
```
git.exe submodule update --progress --init -- "../builder"
fatal: ../builder: '../builder' is outside repository at 'D:/.../memreduct'

git.exe submodule update --progress --init -- "../routine"
fatal: ../routine: '../routine' is outside repository at 'D:/.../memreduct'
```
I tend to agree with git: putting submodules out of working copy isn't a best practice. And I guess, a conflict with hashes may happen if two or more projects at the same level use same submodule.

**Comment by henrypp** [comment]
It does not neededed.

All links required for compilcation is contained in .[gitmodules](https://github.com/henrypp/memreduct/blob/master/.gitmodules), who need successfull process of compilation it will clone required repos contatined in file.

Compilation process is VERY simple, so it does not need any instruction process or other bullshit.

Who need, - will compile, who don't - come up with a reason.
