### ISSUE TITLE
[Feature]: please provide an win-arm64 release

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [henrypp/memreduct#187]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

I'm using a device with an ARM processor, hope you can provide an arm64 release

### Suggested solution

sorry

**Comment by henrypp** [comment]
You are can't read?
