### ISSUE TITLE
[Feature]UI Update

### ISSUE THREAD

**Issue by NEPaladin** [henrypp/memreduct#190]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.4

### Problem you are trying to solve

This app is quite useful. But the GUI it has is bit ugly to newer OS. That will provide a much better environment. Although it'll cause more memery in need...

### Suggested solution

If you can update to WinUI3?

**Comment by henrypp** [comment]
WinUI3? You tell me to rewrite my code to shitty C#?
