### ISSUE TITLE
New language suggestion

### ISSUE THREAD

**Issue by Markingdeveloper** [henrypp/memreduct#195]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Latest

### Problem you are trying to solve

Just want to add new language

### Suggested solution

Hi Henry++ Community.
I want to add Azerbaijani language to Mem Reduct program.Sorry I didn't know much about C, I am absolutely new to this.Can I add Azerbbaijani language to this program?

**Comment by Markingdeveloper** [comment]
Hope I explained well:)

**Comment by henrypp** [comment]
just create pull request
