### ISSUE TITLE
[Bug] Middle Click Not Working on Tray ICON

### ISSUE THREAD

**Issue by Sahil12524** [henrypp/memreduct#196]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4 Release

### Windows version

Windows 11 Pro

### Steps to reproduce

1. Go to tray icon
2. Middle click to clean memory

### Expected behavior

Memory must be cleaned.

### Actual behavior

Middle click is acting like a left click, the window is getting opened instead of cleaning memory.

### Logs

N/A

**Comment by henrypp** [comment]
its fucking windows 11 bug, not mine, windows 11 does not process middle click on tray, i dont know why
