### ISSUE TITLE
[Feature] Windows 7 Support

### ISSUE THREAD

**Issue by L8X** [henrypp/memreduct#198]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

N/A

### Problem you are trying to solve

I'm not sure if you are aware, but Windows 7 has an active user base and community backing it, which includes myself, and I would like to request that you look into support for Windows 7.

There are many applications out there that maintain support for Windows 7 due to it's popularity among advanced users and digital privacy advocates, and as far as I am aware, is is very simple to add support for Windows 7 as the libraries within Windows are decently similar between 7 and 8 / 8.1, of which you support already.

### Suggested solution

Adding support for Windows 7 would increase the amount of people your application would be usable by, therefore increasing the chance of gaining new followers and users.
I used this software a while back on Windows 10 and was amazed by it, however now that I have switched to Windows 7, I cannot use it.

**Comment by henrypp** [comment]
you cant run it on win7 or waht?
