### ISSUE TITLE
[Bug] memory cleaning don't work every Minute 

### ISSUE THREAD

**Issue by Grimfoxy19883** [henrypp/memreduct#199]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

newest

### Windows version

window 11

### Steps to reproduce

![image](https://github.com/henrypp/memreduct/assets/77354034/0f3dcbc5-f142-4440-be83-3b46838327ef)

### Expected behavior

it would clean the memory every Minute 

### Actual behavior

it didn't clean memory at all and counted it as disabled.

**Comment by henrypp** [comment]
its not true, all works
