### ISSUE TITLE
WARNING Win7 64bit!

### ISSUE THREAD

**Issue by ghost** [henrypp/memreduct#20]
Although release_3.2 works well with 64bit architecture, unfortunately at every boot displays a warning (see attached file).
How to disable that warning?

![warning win7 64bit](https://cloud.githubusercontent.com/assets/24399421/20907622/ac788576-bb4f-11e6-8833-6891144fe158.jpg)

**Comment by henrypp** [comment]
what problem? use 64-bit executable!
