### ISSUE TITLE
[Question]command line guide

### ISSUE THREAD

**Issue by adamp4** [henrypp/memreduct#200]
Hi Henry,

Thanks a lot of sharing such a good app, i've been used it for years.
I try to run "memreduct /?" to get command line guide but seems it doesn't work.
I'v noticed update info which you mentioned a issue#84, then i tried "memreduct -clean" but there's always a notification window when it's done like pic below, could it be skipped?
It would be very helpful if you could add command line guide.
Thanks again ^^

Best wishes
Adam

**Comment by henrypp** [comment]
you cant use '-help'?
