### ISSUE TITLE
Mem Reduct Admin rights at system startup.

### ISSUE THREAD

**Issue by Michael86555** [henrypp/memreduct#202]
Hello. Is it possible to run Mem Reduct with admin rights at system startup? I tried the task scheduler but it didn't work. The problem is that auto cleaning and keyboard shortcut cleaning do not work unless I click the "clean" button with administrator rights in the program or when I run the program with administrator rights manually, which is a pain for me.

---

App version: <3.4>
Windows version: <Win 11 23H2>

**Comment by henrypp** [comment]
you have not worked task scheduler and u want i can solve this problem? i not telepayh, it ur system, not mine.
