### ISSUE TITLE
[Question] does this program write to SSD?

### ISSUE THREAD

**Issue by useless642** [henrypp/memreduct#203]
hi, I just wanted to know if this program works by writing to SSD when freeing memory?

I configured it to clean memory every 5 minutes, but I'm worry if it actually writes to SSD to be able to work?

(I'm worry about SSD lifespan, lol)

---

App version: 3.4
Windows version: Windows 10, 64-bit

**Comment by PH7N** [comment]
When the operating system moves data from RAM to the page file, it might involve writing data to the storage drive, including an SSD if that's where the page file resides. This action, however, is managed by the operating system itself, not specifically by Memreduct.

**Comment by henrypp** [comment]
answered

**Comment by useless642** [comment]
> (I'm worry about SSD lifespan, lol)

is this something to worry about?

**Comment by henrypp** [comment]
dont use computer if u worry
