### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by MaxAlekseyev** [henrypp/memreduct#204]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.3.2

### Problem you are trying to solve

It will be fine to make able to use Memreduct via CLI

### Suggested solution

It will be fine to make able to use Memreduct via CLI

**Comment by henrypp** [comment]
u cant memreduct --help?
