### ISSUE TITLE
[Bug] 100% hard disk

### ISSUE THREAD

**Issue by Min63214** [henrypp/memreduct#205]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4.0

### Windows version

Windows 10

### Steps to reproduce

1: instal the versiond and install.
2: crean the RAM
3: the Hard disk is at 100%

### Expected behavior

do not take the hard drive to 100%

### Actual behavior

take the Hard drive to 100%

### Logs

When I clean the memory, it does clean, but after that the hard drive is always used at 100%.

**Comment by henrypp** [comment]
pizdish kak dishish
![sshot-001](https://github.com/henrypp/memreduct/assets/3902025/82c15afa-b1eb-4180-9655-5ff882ed44a8)
