### ISSUE TITLE
Notification Bug

### ISSUE THREAD

**Issue by Crocodile73** [henrypp/memreduct#212]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

Windows 11 (23H2)

### Steps to reproduce

Run the program, manual clean, or scheduled clean
Notification boxes displays with memory free'd up
Box has odd title at top called. notifyicongeneratedaumid_842407269

### Expected behavior

![unknown_2024 02 15-15 40](https://github.com/henrypp/memreduct/assets/16454525/8e3610ef-3c35-4472-af28-071f09d05643)

### Actual behavior

Only started after a language update

**Comment by henrypp** [comment]
dont have this, and in src code i dont use, as u see, this shit

and even dont know where it come from, google it

**Comment by Initial-heart-1** [comment]
> ![image](https://private-user-images.githubusercontent.com/91740046/328548036-5f89b085-2ead-4345-a40b-8743b9f193ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjQ2MTcsIm5iZiI6MTcxNTEyNDMxNywicGF0aCI6Ii85MTc0MDA0Ni8zMjg1NDgwMzYtNWY4OWIwODUtMmVhZC00MzQ1LWE0MGItODc0M2I5ZjE5M2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDIzMjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzY1MWNiNGY0YTY0MzU0NzIxYjg4ODg5YjJkZDZjYjc4MGY4NjBkNTU3MmMyMWI4MThiZTg0ZjdmYTEyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iA_ODUoBbKfOYB0pv8tES3eDRVTCPJVV2O6iqiucceY)
> 
> This strange notification icon will also appear

it looks normal
if u want to turn it off: Settings → Tray Icons → Balloon tips
just uncheck both checkboxes

**Comment by Yuzgaf33tref6** [comment]
> > ![image](https://private-user-images.githubusercontent.com/91740046/328548036-5f89b085-2ead-4345-a40b-8743b9f193ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjQ2MTcsIm5iZiI6MTcxNTEyNDMxNywicGF0aCI6Ii85MTc0MDA0Ni8zMjg1NDgwMzYtNWY4OWIwODUtMmVhZC00MzQ1LWE0MGItODc0M2I5ZjE5M2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDIzMjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzY1MWNiNGY0YTY0MzU0NzIxYjg4ODg5YjJkZDZjYjc4MGY4NjBkNTU3MmMyMWI4MThiZTg0ZjdmYTEyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iA_ODUoBbKfOYB0pv8tES3eDRVTCPJVV2O6iqiucceY)
> > 
> > This strange notification icon will also appear
> 
> it looks normal
> if u want to turn it off: Settings → Tray Icons → Balloon tips
> just uncheck both checkboxes

thanks！
