### ISSUE TITLE
Mouse change to default settings after cleaning [Bug]

### ISSUE THREAD

**Issue by Pinoles17** [henrypp/memreduct#215]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

W10 Pro 22H2

### Steps to reproduce

![Sin título](https://github.com/henrypp/memreduct/assets/138397475/dbf8c304-27d0-42f7-aba4-f78da7bcfe04)

### Expected behavior

Is there any way to avoid this folder to get deleted?

![image](https://github.com/henrypp/memreduct/assets/138397475/85093573-e74a-4f2f-bc19-0137607ed054)

### Actual behavior

The temporal mouse folder, where the config is, gets deleted and mouse restarts to default

**Comment by henrypp** [comment]
> Is there any way to avoid this folder to get deleted?

not in any way i working with this directory
