### ISSUE TITLE
Does memreduct help with memory leaks? if so what settings?[Question]

### ISSUE THREAD

**Issue by Tiberiusmoon** [henrypp/memreduct#216]
Hi,
I have a game that generates a memory leak after 10-12hours of use. (observed by streamers)
From what I understand its when a game allocates ram but then fails to release it which accumulates and causes crashes.
Does one of Memreduct's settings clean up such issues?

**Comment by Initial-heart-1** [comment]
Default settings should already cleanup some memory leaks.
Just configure timer(Clean every) and cleanup threshold(Clean when above).
It should work.
By the way, I would personally not recommend creating an issue for such questions. You might be able to find answer using a search tool such as Google. Or, you can just experiment with it. This software doesnt need a lot of difficult configuration to use.

**Comment by henrypp** [comment]
completely not, but it can help for cleaning up up for such thingss
