### ISSUE TITLE
[Question] Request a new release with all changes since v3.4

### ISSUE THREAD

**Issue by Initial-heart-1** [henrypp/memreduct#217]
This software works so well that I've been installing it for all my devices, and I've also been installing it for others who have asked me to optimise or install Windows on their devices.
However, the latest release was in 2022. I've noticed that this repository has been kept active, but there aren't any new releases. Whilst I can receive updates from Internet right after installing it, I would like these updates to be provided at setup so that I don't have to be online to install updates after installing for this software.
If it is awkward to do so, please tell me why.
Thanks.

**Comment by henrypp** [comment]
it is not finished yet, i publich when it is finish
