### ISSUE TITLE
如果能整成加速球的形式，并显示网速流量监控，双击可加速优化内存，那就太棒了。

### ISSUE THREAD

**Issue by ednykissyou** [henrypp/memreduct#223]
如果能整成加速球的形式，并显示网速流量监控，双击可加速优化内存，那就太棒了。
(If it can be integrated into the form of accelerated balls and shows the surveillance of network speed traffic. Double -click to accelerate the optimized memory, which is great.)

**Comment by henrypp** [comment]
idk chn, and network speed in memery tool is out of logic

**Comment by Initial-heart-1** [comment]
你是否在找......360/tencent/2345/kingsoft
加速球没有任何用 除了看着好看 花里胡哨 该软件本身可用的自动清理能够更静默的清理
有网速监控需求不妨考虑使用专门软件解决。
（@henrypp He was talking about a popular floating window in Chinese security software like this:
![ChMkK2R0c7GIOc1lAAETsDtpm7UAAGRZQGfIh0AARPI443](https://github.com/henrypp/memreduct/assets/63091661/3c31f805-b65e-40db-b928-6d85a64aeba7)
It works like memreduct. single- or double-click to clear.
What makes the difference is that it's more obvious and has a stupid dynamic for comfort :(
）
