### ISSUE TITLE
There will be a short stuck, not so silky to use. Especially when optimizing memory, it will be stuck for a while.

### ISSUE THREAD

**Issue by ednykissyou** [henrypp/memreduct#224]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

win11

### Steps to reproduce

There will be a short stuck, not so silky to use.
Especially when optimizing memory, it will be stuck for a while.

### Actual behavior

There will be a short stuck, not so silky to use.
Especially when optimizing memory, it will be stuck for a while.

### Logs

There will be a short stuck, not so silky to use.
Especially when optimizing memory, it will be stuck for a while.

**Comment by Initial-heart-1** [comment]
pls check ur settings
several of the checkboxes shown in this image should remain unchecked:
![image](https://github.com/henrypp/memreduct/assets/63091661/6b386a28-ca9b-4b50-8416-b80d5897a2f4)
by the way:DO NOT submit any issue as a ‘bug’ until you are sure it is a bug
