### ISSUE TITLE
[Bug]The middle button function of the mouse is malfunctioning

### ISSUE THREAD

**Issue by QiuLiang-99** [henrypp/memreduct#226]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Version 3.4 Release,64-bit (Unicode) (c)2011-2022 Henry++.All Rights Reversed.

### Windows version

Vindows11专业版 23H2  22631.3593

### Steps to reproduce

1.Set the middle mouse button to clear memory in the settings
2.Click on the taskbar icon with the middle mouse button

### Expected behavior

clean RAM

### Actual behavior

Do not clean RAM

### Logs

when I used this software in win 10，its worked good. Seems like the problem Related to win 11

**Comment by QiuLiang-99** [comment]
Set double clicking with the mouse to clear memory in the settings, and check the option to open a window with a single left or middle click to clear memory.By the way ,I use simplified chinese.

**Comment by QiuLiang-99** [comment]
In the settings, set double-click to clear memory, and check the option to open windows with a single click, causing the effect of a single left or middle button click to clear memory.

**Comment by Initial-heart-1** [comment]
Unable to duplicate this issue. It has been tested in the same environment (using the Simplified Chinese version) and everything works fine.
Need more information.

**Comment by Initial-heart-1** [comment]
maybe u can provide a screenshot of ur settings and a video of ur operation
which may be able to help with this issue

**Comment by QiuLiang-99** [comment]
https://github.com/henrypp/memreduct/assets/125732151/3dfec8e8-6f7e-40ea-be12-9365c04b1725
well,As you can see,its just happen

**Comment by henrypp** [comment]
it is not my problem, it is idiotic win11 problem which was corrected at win11 24h2 26100+

**Comment by Initial-heart-1** [comment]
> it is not my problem, it is idiotic win11 problem which was corrected at win11 24h2 26100+

oh i guessed so at first
(BJT,UTC+8) i contacted the author last night and tried to confirm it but after trying for a long time we couldnt build the project even after importing `routine`
just found a commit from 9 years ago and then confirmed that the problem might be around line 2030
even though you've confirmed that the problem is coming from Windows,id like to ask if theres some documentation that could be provided to make it easier for others to build or troubleshoot?

**Comment by henrypp** [comment]
@Initial-heart-1 it reported over 9000 times,    u can google it, m$ required 3.5 year to fix it and there was no documentation

**Comment by Initial-heart-1** [comment]
> @Initial-heart-1 it reported over 9000 times, u can google it, m$ required 3.5 year to fix it and there was no documentation

i see but what i meant was can u provide documentation for memreduct
after seeing ur comment i confirmed problem via SEO
but on trying to trace problems back to last night i found memreduct had no documentation on build or troubleshooting
not even anywhere that said where to get the 'routine' from (Although i did find it)
so can u provide some simple documentation for these?
