### ISSUE TITLE
[Bug]Translation mistakes in Chinese Simplified and Chinese Traditional after a recent language update.

### ISSUE THREAD

**Issue by Nothing9495** [henrypp/memreduct#227]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

Windows 11 24H2 (26100.560)

### Steps to reproduce

it happened after an language update was applied to Mem Reduct (not the system language pack update)
Mem Reduct popped up a window after my computer has started, telling me there is a language update available, and I applied the update without looking through it carefully. Then I found the translation in Chinese (both Simplified and Traditional) became incorrect.
That happens in many places from the main window to the settings window, and it has caused me some troubles, letting me have to use English for a while.

You can see the problem trough the attacthments.
![屏幕截图 2024-06-14 155022](https://github.com/henrypp/memreduct/assets/90544246/5140ba2a-ac86-49ef-b731-6ba3e9a53152) ![屏幕截图 2024-06-14 155136](https://github.com/henrypp/memreduct/assets/90544246/52727dc3-70e8-4818-b4dd-b6f8402f12f1)

![屏幕截图 2024-06-14 155040](https://github.com/henrypp/memreduct/assets/90544246/b7b1c7f6-b3e2-486b-802c-d114689e9cfb) ![屏幕截图 2024-06-14 155142](https://github.com/henrypp/memreduct/assets/90544246/8cbcc00c-4c9d-4570-b5d2-bc6662b03093)

![屏幕截图 2024-06-14 155046](https://github.com/henrypp/memreduct/assets/90544246/3655ef87-a6ff-476b-b380-c5bc87b5dbd8) ![屏幕截图 2024-06-14 155149](https://github.com/henrypp/memreduct/assets/90544246/67106fbd-527e-4dfa-b97c-d00cdf598c79)

![屏幕截图 2024-06-14 155055](https://github.com/henrypp/memreduct/assets/90544246/01f455c4-51d1-46cd-865e-21edd4941a46)
![屏幕截图 2024-06-14 155200](https://github.com/henrypp/memreduct/assets/90544246/baaa3252-be7d-4791-96c9-8fd541276894)

![屏幕截图 2024-06-14 155109](https://github.com/henrypp/memreduct/assets/90544246/5c6a5b2e-4b35-4184-9e09-8571fd2c0669)
![屏幕截图 2024-06-14 155214](https://github.com/henrypp/memreduct/assets/90544246/a3504cf6-7ad8-4f3a-93ed-b1ff8e5a675c)

### Expected behavior

Chinese translation is correct.

### Actual behavior

they are not correct.

**Comment by Initial-heart-1** [comment]
+1

**Comment by Nothing9495** [comment]
looks like those text in chinese are misplaced?

**Comment by Initial-heart-1** [comment]
> looks like those text in chinese are misplaced?

yeah i think this is because of some recent code commits because there appear to be no language file related changes in commits

**Comment by henrypp** [comment]
you can change locale and i will update it (in this repo/made pull request), okay?
