### ISSUE TITLE
[Bug] The content displayed in the Chinese interface is misplaced.

### ISSUE THREAD

**Issue by RepentStar** [henrypp/memreduct#228]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v.3.4 

### Windows version

Windows11 23H2

### Steps to reproduce

1. Launch the application 2. Switch the language to Chinese

### Actual behavior

![memreduct_DFvPEJnLqv](https://github.com/henrypp/memreduct/assets/87593085/98554b17-7be0-4839-8dd3-82c49e08625f)
![memreduct_70O2hkhWb8](https://github.com/henrypp/memreduct/assets/87593085/c01a86e9-0137-4457-b381-a0cf01d2b56d)
It is enough to see from these two pictures that the language content has been misaligned. In fact, there are more misalignments. Please check the mapping table. Thank you.
My English is not good, so I use a translator, if there is anything you can not understand please ask.:)

**Comment by henrypp** [comment]
[u did not hear](https://github.com/henrypp/memreduct/issues/227#issuecomment-2168590412)?
