### ISSUE TITLE
[Bug] Turkish language broken after update 2 weeks ago

### ISSUE THREAD

**Issue by emir814** [henrypp/memreduct#230]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4

### Windows version

11

### Steps to reproduce

With the update 2 weeks ago, the Turkish language is completely broken, for example it says Exit instead of Settings.

### Expected behavior

0

### Actual behavior

As a solution, I solved the problem by switching to the memreduct.lng file from 2 months ago

### Logs

0

**Comment by Nothing9495** [comment]
It in fact happens in every language except English after a Language Pack update that you mentioned. I found the fact just a few minutes ago after I tried other language options.

**Comment by henrypp** [comment]
fixed
