### ISSUE TITLE
[Feature] I recommend optimizing chrome and firefox these two browser applications.

### ISSUE THREAD

**Issue by rfrkk** [henrypp/memreduct#232]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [x] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3..4

### Problem you are trying to solve

Since Chrome and Firefox consume a lot of memory and affect computer performance, I recommend optimizing special modes for these two browser applications.

Special mode optimization options:
1. Start or shut down
2. Select the applications to be processed: chrome and firefox can be selected individually or all
3. Memory cleaning frequency (milliseconds): 500~600000 milliseconds
4. At least how much memory is occupied (add the total) before clearing the memory (Mb): 10~600 Mb

For example, I want to perform special mode optimization on chrome (orange box) and firefox (blue box). First, I find the special mode optimization option, then activate the check box, select chrome and firefox, select 6000 milliseconds for memory cleaning frequency, and finally at least Fill in the amount of memory occupied by 100Mb and complete.

Then every 7000 milliseconds, it checks whether the total number of all chrome.exe reaches 100Mb, achieving immediate memory clearing. At the same time, it also checks whether the total number of all firefox.exe reaches 100Mb, which means clearing the memory immediately.

I have been your Mem Reduct fan since 2019. Since these two browsers have developed rapidly in the past few years, they have also become memory-eating monsters. Although memory optimization has been set, the performance is still poor, so I hope the developers can help us Evaluate the feasibility of this feature

### Suggested solution

As mentioned above, tks.

### Screenshots / Drawings / Technical details

![p201](https://github.com/user-attachments/assets/9a88db7e-5ad9-4896-a456-8c8a583ebe73)

**Comment by ubless607** [comment]
I think it is related to this 3rd-party software.
https://rizonesoft.com/downloads/firemin/

**Comment by henrypp** [comment]
no
