### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NkeoPatch** [henrypp/memreduct#236]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

0c56c58

### Windows version

19044.3086

### Steps to reproduce

run build_vc.bat

### Expected behavior

build the program

### Actual behavior

some files are missing
![image](https://github.com/user-attachments/assets/7bf3a9a4-8cd4-4ed2-990f-1432c78a64da)

**Comment by henrypp** [comment]
[duplicate](https://github.com/henrypp/simplewall#reviews-of-idiots)

**Comment by NkeoPatch** [comment]
> [复制](https://github.com/henrypp/simplewall#reviews-of-idiots)

So how to use .gitmodules? idk how to make it work

**Comment by NkeoPatch** [comment]
> [复制](https://github.com/henrypp/simplewall#reviews-of-idiots)

Thx bro, It works
