### ISSUE TITLE
[Bug] Menu Chinese (Simplified) translation text 

### ISSUE THREAD

**Issue by eruditus-ginkgo** [henrypp/memreduct#239]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.4 (Language Pack 13-09-2024  20:05:20)

### Windows version

Windows11

### Steps to reproduce

Download and install update [Language Pack 13-09-2024 20:05:20].

### Actual behavior

The text of the menu options appears misaligned. For example, the Exit button is displayed as “Settings”, Clear Memory is displayed as “Clear Interval”, and so on.

Has the new version changed the parameter names of some translation files? The original translations in this [i18n file](https://github.com/henrypp/memreduct/blob/master/bin/i18n/Chinese%20(Simplified).ini) are normal.

Is it because the order has changed due to the addition of a few new lines? I noticed that the _memreduct.lng_ file is organized by sequential number. If you need help with Chinese, please ask.

> IDS_UPDATE_DONE=Downloading update finished.
> IDS_UPDATE_ERROR=Update server connection error.
> IDS_UPDATE_INIT=Checking for new releases...
> IDS_UPDATE_INSTALL=Update available, do you want to install them?

**Comment by xiaoweiXX** [comment]
I have the same problem. All texts are in disarray.

**Comment by fsjoy52** [comment]
The update language pack provided seems to be problematic, so my solution is not to update the language pack that the program prompts to update.

**Comment by henrypp** [comment]
now it looks OK

**Comment by xiaoweiXX** [comment]
> 现在看起来还不错

I didn't find any updates. How could I fix this problem?

**Comment by xiaoweiXX** [comment]
> now it looks OK

I didn't find any updates. How could I fix this problem?

**Comment by henrypp** [comment]
@xiaoweiXX sorry, i forgot update VERSION file, i do when i come back to home ;)

**Comment by henrypp** [comment]
done!

**Comment by xiaoweiXX** [comment]
> done!

How could I find the update? I tried to check update in MemReduct, but there is no update.

**Comment by xiaoweiXX** [comment]
> done!

Oh, it seems that my network is not good. I checked update without net tool, and find the update.

**Comment by TKASAKAWA** [comment]
This tool resides at multiple workstations
24 hours available

Thank you for your maintenance.

**Comment by henrypp** [comment]
@TKASAKAWA ok

**Comment by windy1021** [comment]
Sorry, excuse me. How can I obtain an update to fix bugs? I tried to obtain an update in the software but there seems to be no prompt for me to have update content. I also didn't find a new release in the repository.Could you provide a website? Thanks.

**Comment by henrypp** [comment]
@windy1021 you dumb? all in this repo, localization maybe downloaded automatically, idk...

**Comment by xiaoweiXX** [comment]
> Sorry, excuse me. How can I obtain an update to fix bugs? I tried to obtain an update in the software but there seems to be no prompt for me to have update content. I also didn't find a new release in the repository.Could you provide a website? Thanks.

Do not use any net tool like clash, just check update directly, then you should find the update.
