### ISSUE TITLE
[Question] Some text has not been i18n

### ISSUE THREAD

**Issue by Initial-heart-1** [henrypp/memreduct#245]
![sc1](https://github.com/user-attachments/assets/3de6a291-4aaa-4866-9b8b-dca599e43b33)
![sc2](https://github.com/user-attachments/assets/204be36b-a5d9-468b-ae7b-b904c126ff62)

**Comment by Initial-heart-1** [comment]
![image](https://github.com/user-attachments/assets/d0336b87-d3be-40ae-b2f2-995ae331f58a)

**Comment by henrypp** [comment]
i think it do not required to translate

**Comment by Initial-heart-1** [comment]
> i think it do not required to translate

this makes UI style a bit non-uniform
and at least based on my experience there may be a number of users who cant read somewhat longer English lines
so not translating those parts that could cause problems could lead to problems for some users, special Warning
of course users should be responsible for their own actions, so it's not necessary but maybe could be translated
