### ISSUE TITLE
[Question] False Positive

### ISSUE THREAD

**Issue by Sahil12524** [henrypp/memreduct#246]
I just installed the app, the installer completed the installation successfully. When I pressed finish on setup the defender triggered it as a virus.
![image](https://github.com/user-attachments/assets/d05cf84e-547a-460f-8120-fd8af7aba3c3)
![image](https://github.com/user-attachments/assets/d33007f7-cc9b-4410-955c-0f5e8673c1e3)
what went wrong?

---

App version: <3.5>
Windows version: <11>

**Comment by henrypp** [comment]
dont know, i dont use defender, this bullshit which becomes billionaire company, and still cannot get correct virus names, it is stupid!
