### ISSUE TITLE
[Bug] V3.5 can NOT show icon on traybar

### ISSUE THREAD

**Issue by peter8777555** [henrypp/memreduct#247]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

V3.5

### Windows version

Windows 11 traditional Chinese(23H2 22631.3672)

### Steps to reproduce

Just run memreduct.exe

### Actual behavior

V3.4 no this issue.

**Comment by henrypp** [comment]
#243

**Comment by peter8777555** [comment]
[Bug] Some question after upgrade to v3.5 #243
It is no good title.

"Problems trying to put MR in "Program Files" folder: Tray icon is not displayed, but continues to run in the background after MR is minimised."

**Comment by Initial-heart-1** [comment]
> [Bug] Some question after upgrade to v3.5 #243 It is not good title.
> 
> "Problems trying to put MR in "Program Files" folder: Tray icon is not displayed, but continues to run in the background after MR is minimised."

ur right
this issue first reported a fatal error, which was resolved
however, it has since been found that maybe there are other little problems and they all occur in v3.5, so title has simply been changed. I hope this gives a good overview of the issue, but it seems to have backfired

**Comment by peter8777555** [comment]
In Chinese below,
我看到你在 吾爱破解 的帖子才知道有更新,
在 Windows 11 测试 目前只有 托盘不显示图标,
吾爱破解 无法认证 台湾 手机号,
只能看帖 无法 发/回帖.

**Comment by Initial-heart-1** [comment]
> In Chinese below, 我看到你在 吾爱破解 的帖子才知道有更新, 在 Windows 11 测试 目前只有 托盘不显示图标, 吾爱破解 无法认证 台湾 手机号, 只能看帖 无法 发/回帖.

https://github.com/henrypp/memreduct/issues/243#issuecomment-2550901166
重启电脑或许也可解决问题 应该是Windows的问题

**Comment by peter8777555** [comment]
不急着用,
等 作者 释出新版 再更新.
