### ISSUE TITLE
Thanks !!!!

### ISSUE THREAD

**Issue by seamen34** [henrypp/memreduct#250]
No problem, thanks for the program!!!
For the new issue that you are not throwing support!!!!

**Comment by henrypp** [comment]
ok, youre welcome! and where is question?

**Comment by Initial-heart-1** [comment]
@henrypp I think this should be closed

@seamen34 Please DO NOT open an issue without any questions
this can be unnecessarily difficult even though it might not be your intention

**Comment by seamen34** [comment]
And everything is clear to me, everything works perfectly without problems and even in Russian, thanks for all this!
