### ISSUE TITLE
[Bug]window with square corners after applying fix in issue #243

### ISSUE THREAD

**Issue by Nothing9495** [henrypp/memreduct#252]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.5.0

### Windows version

24H2 26100.2605

### Steps to reproduce

1. install memreduct version 3.5
2. apply the fix provided in issue #243 _(to solve the problem that memreduct doesn't run properly)_.
3. run memrreduct.exe, and you'll see the square window corners instead of rounded ones.

### Expected behavior

window with rounded corners

### Actual behavior

window with square corners

**Comment by Nothing9495** [comment]
forgot to attach the screenshot, here it is.
![image](https://github.com/user-attachments/assets/58a307b5-9887-4079-b5fb-6fa8c312b414)

**Comment by Nothing9495** [comment]
forgot to attach the screenshot, here it is.
![image](https://github.com/user-attachments/assets/5be97fb0-796a-48da-9422-4719edb4efff)

**Comment by henrypp** [comment]
tomorrow you can add this option to main INI:
```ini
IsWindowCornerRound=true
```
