### ISSUE TITLE
[Bug] don't show tray icon in vr 3.5.1

### ISSUE THREAD

**Issue by wolfkingal2000** [henrypp/memreduct#254]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.5.1

### Windows version

Edition	Windows 10 Pro Version	22H2 Installed on	‎1/‎15/‎2022 OS build	19045.2486 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Steps to reproduce

Open - don't show tray icon 

### Actual behavior

![image](https://github.com/user-attachments/assets/f365754f-e826-4699-bf83-ab8fd031be50)

**Comment by Initial-heart-1** [comment]
[look at this](https://github.com/henrypp/memreduct/issues/243#issuecomment-2550901166)

**Comment by Initial-heart-1** [comment]
[look at this](https://github.com/henrypp/memreduct/issues/243#issuecomment-2550901166)

**Comment by henrypp** [comment]
solution https://github.com/henrypp/simplewall/issues/1695#issuecomment-1885857698

**Comment by hairycactus** [comment]
On my system, _Mem Reduct_ shows the following behaviour:
- `v3.5.1 x64` Portable: Systray icon present; Has [`Start Minimized` bug](https://github.com/henrypp/memreduct/issues/258)
- `v3.5.0 x64` Portable: Systray icon missing; No `Start Minimized` bug

OS: Win10 r1909 v18363.418 x64 Home
