### ISSUE TITLE
Crash with server 2012 r2

### ISSUE THREAD

**Issue by Yves45300** [henrypp/memreduct#28]
The software is nice, but crash on windows 2012r2 operating system after cleaning.
we have a 128 Gb RAM server and if the memory is used arround or more than 30%, your software do the job and crash . if the memory is low, no any problem

**Comment by henrypp** [comment]
Try to disable "Show memory clean result" and repeat tests.

**Comment by Yves45300** [comment]
Ok, thanks
I try

De : Henry++ [mailto:notifications@github.com]
Envoyé : mardi 29 août 2017 14:23
À : henrypp/memreduct <memreduct@noreply.github.com>
Cc : GOERING Yves <yves.goering@mipe.fr>; Author <author@noreply.github.com>
Objet : Re: [henrypp/memreduct] Crash with server 2012 r2 (#28)


Try to disable "Show memory clean result" and repeat tests.

**Comment by henrypp** [comment]
> Ok, thanks
> I try

So what?

**Comment by Yves45300** [comment]
So good
Thanks

Cordialement
Envoyé de mon téléphone.
Yves Goering

________________________________

**Comment by henrypp** [comment]
3.2.2 fixed
