### ISSUE TITLE
请问此种清理内存方式会否产生问题

### ISSUE THREAD

**Issue by Sealt** [henrypp/memreduct#32]
清理内存后是否会对系统运行造成不可预知的问题？即使当前并没有显现出来。

**Comment by henrypp** [comment]
@Sealt, in english, please!

**Comment by Sealt** [comment]
Will there be any unpredictable problems with my system after using your tools?. Most of China's memory cleanup applications are suppressing memory to virtual memory, resulting in frequent applications, re loading memory, or slow virtual memory, resulting in Caton.

**Comment by oldmenplus** [comment]
win10系统，7月份的版本。
用adobe的软件的时候很容易出现蓝屏，系统崩溃啦。打开Chrome页面多了也有一定机会蓝屏。
我设置10分钟清理一次，是我设置错了嘛？
の_の 对于CPU是1400，多开各种软件无压力，却只有8G内存的我来说简直福音。
我英语超烂啦，只能用Google翻译，看不懂的话，诶，还真没办法了哦。

==================================================================

Win10 system, version July.
With Adobe software, it is easy to appear blue screen, the system crashed. Open the Chrome page more, there is also a chance blue screen.
I set it up for 10 minutes to clean it up. Did I set it wrong?
In the _ for CPU is 1400, open the software without pressure, but only 8G memory of me is the gospel.
My English is too bad, and can only use Google translation, do not understand the words, ah, really no way out Oh.

**Comment by eebssk1** [comment]
> 
> 
> Will there be any unpredictable problems with my system after using your tools?. Most of China's memory cleanup applications are suppressing memory to virtual memory, resulting in frequent applications, re loading memory, or slow virtual memory, resulting in Caton.

if you tick the extra mem region,yes it is.
你如果够了默认没钩的那两个的话，是有可能会蓝屏或卡死的。

**Comment by Rereyuop** [comment]
Same question here, how does it work?

**Comment by eebssk1** [comment]
> 
> 
> Same question here, how does it work?

Windows internal API,it's already said in README.
