### ISSUE TITLE
Mem Ruct 3.2..2- incorrect display on all figures

### ISSUE THREAD

**Issue by lookingatsoftware** [henrypp/memreduct#34]
I just down loadd this program and used on an old 4 core amd 3mhz system,
running the following operating systems.

Windows XP sp3 Pro 4gb memory.
Windows7 32bit 8gb memory.
Windows7 64bit 8gm memory.

Comparing the figure shown with Microsofts own display.

Nothing is correct.
Page files display is doubled,
 System working set:- shown is so small that the system could not operate at all and yet it works fine with Microsofts own Manage showing the correct full memory available.

The only thing displaying correctly is the 'Physical' display (top of program display).
My friend of mine who owns a computer company who was visiting, also took a look,
and saw the same result as I did.
Great idea for a program, but not woking correctly.

Please please have a look and compare the results with Microsofts own software.
All the best.
Charles.

**Comment by henrypp** [comment]
What mcirosoft own software?
