### ISSUE TITLE
With Adobe software, it is easy to appear blue screen, the system crashed. 

### ISSUE THREAD

**Issue by oldmenplus** [henrypp/memreduct#36]
win10系统，7月份的版本。
用adobe的软件的时候很容易出现蓝屏，系统崩溃啦。打开Chrome页面多了也有一定机会蓝屏。
我设置10分钟清理一次，是我设置错了嘛？
对于CPU是Ryzen 1400，多开各种软件无压力，却只有8G内存的我来说简直福音。
我英语超烂啦，只能用Google翻译，看不懂的话，诶，还真没办法了哦。
の_の

-----------------------------------------------------------------------------

Win10 system, version July.
With Adobe software, it is easy to appear blue screen, the system crashed. Open the Chrome page more, there is also a chance blue screen.
I set it up for 10 minutes to clean it up. Did I set it wrong?
For CPU is Ryzen 1400, more open software, no pressure, but only 8G memory for me, just gospel.
My English is too bad, and can only use Google translation, do not understand the words, ah, really no way out Oh.
の_の

**Comment by AnomSanjaya** [comment]
if you cleaning memory manually, will be crashed too?

**Comment by henrypp** [comment]
same here #48
