### ISSUE TITLE
Start minimized or Minimize to tray at startup (Запускать свёрнутой в трей)

### ISSUE THREAD

**Issue by ABTOP55** [henrypp/memreduct#39]
Здравствуй!
Верни, пожалуйста в настройки опцию — Запускать свёрнутой (Start minimized).
До версии 3.2.2 она была, зачем её убрал - непонятно.
Без этой возможности очень неудобно, когда программа стоит в автозагрузке

Заранее спасибо!

**Comment by henrypp** [comment]
Чтобы запустить со свёрнутыйм окном используйте коммандную строку: `/minimized`
Автозагрузка всегда запускается в свёрнутом режиме.
Не верну, плохая опция.

Issue #37 (eng.)

**Comment by ABTOP55** [comment]
Большое спасибо за подсказку! А можно поинтересоваться, чем плоха эта опция в настройках, из-за чего её убрали?

**Comment by henrypp** [comment]
Не нужна.
