### ISSUE TITLE
Auto Cleaning Issue

### ISSUE THREAD

**Issue by FurqanHanif** [henrypp/memreduct#4]
i have set it's auto clean memory value to 85% , my Ram is at 70% and it auto cleans it and says 19MB released , why is that  ?? this is keeps happening , i thought that it auto clean memory only when it crosses 85%...

**Comment by henrypp** [comment]
Need more info, memreduct.ini content and screenshoot

**Comment by FurqanHanif** [comment]
Fixed , ctrl+F1 hotkey is The Problem , conflicting With Other Program , i change the hotkey and looks like problem fixed... 
Thanks .....

**Comment by henrypp** [comment]
ok, i will be fix hotkey compatibility, thanks!
