### ISSUE TITLE
Can't load on system startup

### ISSUE THREAD

**Issue by Deteriorator** [henrypp/memreduct#43]
I choose load on system startup, but it can't load on system startup.
![s-20171216-115020](https://user-images.githubusercontent.com/31269745/34067117-9f686876-e257-11e7-9424-9bdc9a252ab0.png)

at first,I choose load on system startup
![s-20171216-114936](https://user-images.githubusercontent.com/31269745/34067119-b6f7a04c-e257-11e7-8e37-067d258c6838.png)

after, here's the result
![s-20171216-115001](https://user-images.githubusercontent.com/31269745/34067131-0c68bade-e258-11e7-8880-5adcbdf27913.png)

and, when i open the computer,  it can't load on system startup

**Comment by AnomSanjaya** [comment]
tick the "skip UAC prompt warning" too, coz somtimes the UAC isn't appear while startup

**Comment by Deteriorator** [comment]
tick the "skip User Account Control prompt warning" . Still have this problem
![s-20171216-195308](https://user-images.githubusercontent.com/31269745/34070144-f2be05c4-e29a-11e7-8fe5-9284f0c23294.png)

![s-20171216-195345](https://user-images.githubusercontent.com/31269745/34070145-f2ffc4fa-e29a-11e7-9ea3-63fce66f21b8.png)

**Comment by Deteriorator** [comment]
This is the version 3.3
![s-20171216-115020](https://user-images.githubusercontent.com/31269745/34089404-bd089d12-e3ea-11e7-9e57-bcb361edddfa.png)
![s-20171216-115001](https://user-images.githubusercontent.com/31269745/34089410-c4cea992-e3ea-11e7-9a40-09b32df9b47d.png)

This is the version 3.2.2
![s-20171218-115956](https://user-images.githubusercontent.com/31269745/34089443-031a4968-e3eb-11e7-9b3b-cef8b0555cea.png)
![s-20171218-115941](https://user-images.githubusercontent.com/31269745/34089445-0727e22c-e3eb-11e7-8f48-d5b969470228.png)

Hope to solve this problem

**Comment by henrypp** [comment]
fixed

**Comment by marcoareosa** [comment]
Anyone having this issue on version 3.4 on Windows 11?

**Comment by wizart666** [comment]
> Anyone having this issue on version 3.4 on Windows 11?

Same problem.

**Comment by AnomSanjaya** [comment]
> Anyone having this issue on version 3.4 on Windows 11?

ny case, nope. working as usual

**Comment by 001-lasen** [comment]
> Anyone having this issue on version 3.4 on Windows 11?

Yup
Anyone found a solution?

**Comment by 0sovich** [comment]
Startup does not work in Windows 11 ver 24H2.  
The checkmarks in the necessary checkboxes are set.
Mem Reduct 3.4

**Comment by XXBobus** [comment]
To anyone that is seeing this in 2026. The bug still exists, it still won't open on start no matter what you do in windows settings or in the mem reduct settings. I did find a solution however:

1 Open Task Scheduler
2 Create Task
3 Give the task a name, something like Mem Reduct Autostart
4 Mark "Run whether user is logged on or not"
5 Mark Run with highest privileges
6 Configure for Windows 10
7 Now go to the Triggers Site and click "New"
8 Click on "Begin the Task" and select "At log on"
9 Delay Task for 30 seconds
10 Make sure the "Enabled" is marked at the bottom left and click "Ok"
11 Then go to the Action Site and click "New"
12 Select the "Start a program" action if it isn't already selected
13 Next to program there will be a button called "Browse"
14 Click on "Browse" and select Mem Reduct's exe
15 Mine was located at: This PC - Local Disk - Program Files - Mem Reduct - memreduct.exe
16 After that click "Ok"
17 Now go to the "Conditions" Site and just uncheck everything that you can uncheck#
18 Finally go to the "Settings" site and check: Allow task to be run on demand /// Run task as soon as possible after a scheduled start             is missed /// if the task fails restart every: 1 min /// Attempt to restart up to: 3 times /// If the running task does not end when requested, force it to stop.
19 At the bottom left it says "If the task is already running, then the following rule applies:" make sure "Do not start a new instance" is selected
20 Press "Okay"


Now everytime you start your pc it will automatically open. However, do note that you won't see it pop up in the icon list, but it will be visible in the task manager. After that mem reduct will work as usual. If you want to save the task for when you reset windows or something, you can go to task scheduler again, then click on "Task Scheduler Library" on the top left, and then search for the name you gave the task. Once you found it, click on it once and then go to the right side and click "export". This way you get a file, and if you set up a new windows for example, you can then go to Task Scheduler, click on "Import Task" at the top right and then select the file you got from exporting. This way it kind of copy pastes the task around.
