### ISSUE TITLE
When cleaning up memory Often blue screen

### ISSUE THREAD

**Issue by scp131** [henrypp/memreduct#48]
Hello, author  . My system is   win10  1709  home edition   .When the system taking up too much memory I use this software to clean up . blue screen often appear  .When the system takes up little memory  This also happens  Could you give  me a reasonable solution?  i will feel  grateful

**Comment by AnomSanjaya** [comment]
Whats u shoud tick the option in Memory Areas? and when u cleaning memory, whats program do u running at that time?

**Comment by 1055169799** [comment]
我给一些用户的电脑上使用这个软件时也会蓝屏。但我自己的不会。我猜是和系统是不是正版有关。

**Comment by softetherserver** [comment]
No, it also takes up a lot of system resources when cleaning up memory. When you use to clean up the memory, you will find that other things are slower, or when you are copying some files to the USB flash drive, do the same thing. It will slow down, and you can use Ctrl+alt+delete to select the job manager and you can see what program is using.

**Comment by CollinChaffin** [comment]
Time to run a memtest sounds like you may have a bad RAM chip.  The methods used to clean mem can balloon RAM before releasing so it may be bluescreening simply because upper parts of RAM are only being used at the point of ballooning.

**Comment by henrypp** [comment]
@CollinChaffinm yes, or another [crooked](https://github.com/henrypp/memreduct/issues/42#issuecomment-410646843) windows update!
