### ISSUE TITLE
Missing routine.h and routine.c files

### ISSUE THREAD

**Issue by nito-kihk** [henrypp/memreduct#5]
Hello,

I can't find routine.h and routine.c anywhere in your repository.
It prevents the project from being built, since we are missing definitions for various methods, such as all the `_r_*` functions.

Could you possibly add it ?

Thanks.

**Comment by henrypp** [comment]
Hello,

routine library has different repository:
http://github.com/henrypp/routine

**Comment by nito-kihk** [comment]
Oh thanks, I missed that.
