### ISSUE TITLE
User Account Control

### ISSUE THREAD

**Issue by Bootlegger39** [henrypp/memreduct#51]
I have the box ticked to skip "user account control" prompt warning but This does not work when booting.

I have to click yes on account control box each  time I boot up to get memreduct 3.3.2 started.

OS--Windows 8.1 Pro

Please advise
Thanks much

**Comment by Bootlegger39** [comment]
Thanks for the response. Not sure what you mean as I have it to start up at boot time is when 
I run into the "user account control" problem.

Thanks

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Hi, I had the same problem in Windows 10 when I set the "Load on system startup" from Mem reduct program settings.

What worked for me:
1. Setting up startup in task schedueler:
https://superuser.com/questions/770420/schedule-a-task-with-admin-privileges-without-a-user-prompt-in-windows-7
2. Add a delay to it  in the properties under the triggers tab.

Br,
Zoli

**Comment by henrypp** [comment]
fixed
