### ISSUE TITLE
Mem Reduction multi user account Windows 10 Issue

### ISSUE THREAD

**Issue by marcomandolino** [henrypp/memreduct#54]
Hi,
M R it's definitively fantastic and it works great. Congratulations!

The only Isuue it's with win 10 multi user account.

Admin it's ok and it startup normally.

With the user account doesn't start at startup.

Schedule works only in the Admin account with MR with full privileges. Also with selected full privileges and with "any/all user" it doesn't start at startup in the user account.

I can start it from the folder app with the user account, but i have to insert the admin psw.

Some suggestion?

**Comment by henrypp** [comment]
fixed

**Comment by marcomandolino** [comment]
Thanks a lot, very kind

best rgds

marco g l :-)

Il giorno dom 10 feb 2019 alle ore 07:30 Henry++ <notifications@github.com>
ha scritto:
