### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by GFOXSH** [henrypp/memreduct#59]
Yesterday I have following massage, but my version is already latest.
![default](https://user-images.githubusercontent.com/15711761/45923825-329bb700-bef9-11e8-9a67-500dde635ca0.png)

**Comment by henrypp** [comment]
Sorry, server-side bug! Fixed.

**Comment by sergeevabc** [comment]
Включаю компьютер — вижу запрос. Жду «Yes», на следующий день история повторяется.

![](https://images.vfl.ru/ii/1545062231/a39a2309/24636290.png)

**Comment by henrypp** [comment]
@sergeevabc 

Думаю memreduct нет доступа на запись в папку из-за UAC.
Попробуй загрузить и переместить в папку программы файл вручную.

https://raw.githubusercontent.com/henrypp/memreduct/master/bin/memreduct.lng
