### ISSUE TITLE
Combine memory lists

### ISSUE THREAD

**Issue by Chilace** [henrypp/memreduct#60]
![2018-09-30 16-05-08 settings](https://user-images.githubusercontent.com/22879802/46257933-05d43a80-c4cb-11e8-8259-e54103646452.png)

What this option means?

**Comment by andyz168** [comment]
memory regions to be cleaned   most do not know what mean .have  Explanation list？

**Comment by Chilace** [comment]
I found this
https://forums.guru3d.com/threads/a-bit-detailed-info-about-memory-combining-in-win10.419262/
