### ISSUE TITLE
[New Feature Request] Monitoring the mem occupation of a specific process

### ISSUE THREAD

**Issue by ilovuxay** [henrypp/memreduct#66]
Hello!
We're players of the Maplestory which is a Nexon(Korea) product. It is also a popular game in China.
The game client is now with a fatal bug : Memory Leak, which causes its memory occupation quickly to reach ~3.2 GB and then crash.  (x86 client)
Occasionally we got to know your app is very effective to the issue: when your app got to run, the memory occupation of Maplestory.exe greatly decreased while it could be running much longer and more stably.
So,  we are wondering if you can add a new feature to the MemReduct: the app can monitor a process (Maplestory.exe), when it reaches 1.5GB, then get to work.

Thank you!

**Comment by henrypp** [comment]
No, memreduct will not implement working with processes at all.
