### ISSUE TITLE
Feature request: File cache cleaning as in cleanmem

### ISSUE THREAD

**Issue by CollinChaffin** [henrypp/memreduct#69]
If you haven't already I'd like to request you take a look at this freeware/shareware util that is very similar but has some features that would be really nice additions to memreduct depending on your roadmap.  Specifically, I'm interested in that utils "Clean file cache" which releases additional to the normal "clean mem".  When I run it side-by-side to memreduct, the tray icons are literally identical and the default mem cleaning on Win7 also renders identical mem reduction so the methods must be the same so I'm hoping that util gives you some additional ideas particularly it's "pro" mode options.  

But, right clicking that util and selecting the "Clean file cache" releases additional that seems to be missing from memreduct so perhaps start with that feature as the request.

Cleanmem:
http://www.pcwintech.com/cleanmem-help

Thanks and awesome job!

**Comment by GFOXSH** [comment]
Current version of MemReduct can already clear the file cache. There is no point in changing anything. henrypp, you can close this issue, here is the video proof:

https://user-images.githubusercontent.com/15711761/122858294-b7be8f80-d322-11eb-8f20-002d13ed9155.mp4
