### ISSUE TITLE
Bug: Timed execution not reliable in shared installation

### ISSUE THREAD

**Issue by CollinChaffin** [henrypp/memreduct#70]
# Issue

Timed execution not reliable in shared installation 

## Detail

Because timed execution is managed by an internal timer callback check with an associated ini config file read/write every execution, any attempt to maintain timer scheduled execution in a portable installation being used by more than one system, fails.

The following observations have been made during testing of this issue:

1. Impossible to safely run as a portable install from a shared cloud location across machines:  Due to this method of storing then reading back an ini value for last execution, multiple systems will all fight over the same ini and cause dangerous loops.
2. Execution is dependent on the ini file existence during execution, and adds small unneeded disk IO for each read/write - not a huge deal but a negative nonetheless
3. Code needs to be maintained just to perform a simple recurring timed schedule task.  

## Proposed Solution

Simple trigger-based scheduled task set to run every XX minutes (per user's selection in settings)

## Solution Detail

The percentage memory test obviously needs to remain a fully internal callback, but the timed does not.  We can use the long-running cleanmem shareware application that has been previously mentioned in other issue(s) simply as an example as it has an excellent track record performing this exact function in exactly the context being recommended.  That app simply creates a scheduled task with a trigger to run every XX min after login.  In the case of cleanmem, it uses a `/startup` switch with a 2nd scheduled strictly "startup" task vs other startup means to ensure the launch after the user logs on.  The periodic triggered task is then scheduled separately to execute without any switches for the quiet cleaning.

Since all scheduled time-based execution would be managed by the local Windows OS, using this method would allow full scalability of a single installation shared across multiple PCs, such as on a NAS, while still allowing the current simple single portable directory installation with the single shared configuration file.

Not only does this approach removes all need of the current and future maintained timer code from the app, but adds several pretty significant improvements currently not implemented that come with native scheduled tasks.  These alone, if implemented in the current model, would require considerable internal code to replicate such as running with a delay (either set or random) after login to allow full startup before first execution, auto-kill of the clean/task upon running more than xx minutes, ensuring system is idle, etc.

It additionally offers the benefit to the end-user of only having to maintain/update the single shared installation of memreduct on a shared storage location.

The only development requirement other than just removing the timed execution portion of the timer callback would be the small amount of code required to support the fairly limited scope of scheduled task management.

**Comment by henrypp** [comment]
> Impossible to safely run as a portable install from a shared cloud location across machines: Due to this method of storing then reading back an ini value for last execution, multiple systems will all fight over the same ini and cause dangerous loops.

> Execution is dependent on the ini file existence during execution, and adds small unneeded disk IO for each read/write - not a huge deal but a negative nonetheless

Mem Reduct reads ini configuration only once and cache params in memory. Write operations executed only when you change configuration.
