### ISSUE TITLE
Adding support for hiding tray icon

### ISSUE THREAD

**Issue by chenyiping1995** [henrypp/memreduct#74]
Would it be possible to add an option to hide the tray icon, and disable the notifications?

You might ask how a user would end up opening up the window again, and here's my proposal.

If the user would like to bring up the main window, they can simply run this program once again to launch the main window. After that they will be able to turn it back on in the Options.

Once again, this small piece of software is very useful and I like it very much! Thank you for your hard work!

**Comment by henrypp** [comment]
> Would it be possible to add an option to hide the tray icon, and disable the notifications?

You can disable notifications in Settings.
