### ISSUE TITLE
Can this software run on the server operating system?

### ISSUE THREAD

**Issue by qtxCoding** [henrypp/memreduct#77]
Can this software run on the server operating system? Such as server2008 operating system, etc

**Comment by stamepicmorg** [comment]
why not? i think - yes.

**Comment by henrypp** [comment]
Yes. But need enable OS GUI.

**server2012+ guide:**
- terminal > `sconfig`
- select 12 (sestore GUI)
- press <enter>
- restart server
- ???
- PROFIT!
