### ISSUE TITLE
start automatically

### ISSUE THREAD

**Issue by suyang320** [henrypp/memreduct#80]
how to set this sorfware start automatically? it can't start automatically on my laptop

**Comment by AmirOVH** [comment]
Yeah it's the same here, the "Load on system startup" option doesn't work.
Proof: [https://cdn.amir.ovh/V324j.gif](url)

**Comment by henrypp** [comment]
@AmirOVH what subj and OS version?

**Comment by AmirOVH** [comment]
It does
[https://cdn.amir.ovh/q8q6W.gif](url)

**Comment by AmirOVH** [comment]
It does.
[](https://cdn.amir.ovh/q8q6W.gif)

**Comment by AmirOVH** [comment]
It does.
[https://cdn.amir.ovh/q8q6W.gif](url)

**Comment by 52885199** [comment]
我遇到了相同的问题,当我在软件上勾选了开机时加载,关闭设置之后,再次打开设置选项还是没有勾选

**Comment by henrypp** [comment]
fixed
