### ISSUE TITLE
Feature request: automatic memory clean via command line parameter

### ISSUE THREAD

**Issue by Ne0niq** [henrypp/memreduct#82]
Hi, Henrypp!!
First of all, thank you very much for your creation! Very useful!

Can you please implement a small feature - ability to start memory clean procedure for memreduct.exe from the command line? For example "memreduct.exe -clean" or something else.

Reason/usablity situation: 
I am using CMD-script which is killing regular resident programs (browser, download manager, etc) and disabling the network before running a game, and after the game was closed my script returning resident programs.

I know about the memory cleaning hotkey, but I hope you agree that in this specific scenario its better to have a command line parameter for memreduct.exe which will work no matter the program is already running or not.

Cheers!

**Comment by moxuanyuan** [comment]
I have the same need because I want to perform a series of automated actions

**Comment by matttcooke** [comment]
+1

**Comment by 593172440** [comment]
+1

**Comment by Ne0niq** [comment]
Hi, there! For those, who still wants to have some trigger to clean RAM without UI, here is a workaround somewhat replacing missing commandline parameter for memreduct: 
I made simple AutoIt script, which sends a hotkey CTRL+F1 globally, which can be used by memreduct. 
How the dscript works: 
first, you only need to set this hotkey to "Clean Memory" in memreduct settings;
when you run memreduct-clean-memory.exe it sends a hotkey CTRL+F1 and closes itself.

[Source + compiled .exe (gdrive)](https://drive.google.com/file/d/1n1tiahUne0b9T5shrPxtG7hhpTL3qd90)
Feel free to change the hotkey in .au3 cource and recompile it. I included MS keycodes text file for convenience.

Cheers!

**Comment by rishi7387** [comment]
> Hi, there! For those, who still wants to have some trigger to clean RAM without UI, here is a workaround somewhat replacing missing commandline parameter for memreduct: I made simple AutoIt script, which launches Memreduct.exe sends a hotkey CTRL+F6 globally, which can be used by memreduct. How the dscript works: first, you only need to set mentioned hotkey to "Clean Memory" in memreduct settings; target derectory is "c:\Program Files\Memreduct"; when you run memreduct-clean-memory.exe it launches memreduct, sends a hotkey CTRL+F6 and closes memreduct after 5 sec.
> 
> [Source + compiled .exe (gdrive)](https://drive.google.com/file/d/1n1tiahUne0b9T5shrPxtG7hhpTL3qd90) Feel free to change the hotkey in .au3 cource and recompile it. I included MS keycodes text file for convenience.
> 
> Cheers!

Check This Before Downloading 
https://www.virustotal.com/gui/file/acc78ad8a8c5c89295d29e104a5c02a23ce6bb32622e000673fd6e32ecffcd50/detection

**Comment by ripton06** [comment]
+1

**Comment by Ne0niq** [comment]
> Check This Before Downloading https://www.virustotal.com/gui/file/acc78ad8a8c5c89295d29e104a5c02a23ce6bb32622e000673fd6e32ecffcd50/detection

Hi. All AutoIt! scripts being false detected by many antivirus software. It's normal situation here. So, please, don't rush and read my initial message more carefully. I said, that my attachment contains the source code. So why would I publish virus source code?... Ridiculous, right?
