### ISSUE TITLE
"Clean every" disables itself

### ISSUE THREAD

**Issue by josejoa** [henrypp/memreduct#86]
Sometimes, and I don't know why, "Clean every" disables itself and won't check anymore to the interval time fixed. The fields appear shady and you can't change the interval time, very annoying, thank you.

**Comment by josejoa** [comment]
Version 3..3.5 64-bit (Unicode)
Right now I have it already with a shady option in "Clean every" in the context menu of the tray icon, that means it won't clean to the fixed time (I have it to 90 minutes), thank you by replying.

**Comment by henrypp** [comment]
"Clean every" option shaded when memreduct does not have admin rights. Do you run under admin?

**Comment by josejoa** [comment]
I run memreduct automatically in settings "Load on system startup". I noticed that when is in shady grey color the "Clean every", after i clean manually with double click in icon tray, then it begins to works the "Clean every" function and clean at the fixed time. But i don't know when it will come again the shady color and stop working... So it's not grave but a little annoying, thanks.

**Comment by henrypp** [comment]
Use Skip UAC to start memreduct always as asmin.

**Comment by josejoa** [comment]
I will try it, thank you.

**Comment by josejoa** [comment]
Do you know a method to free virtual memory (paged memory)? Because this program only frees hte phisical memory, and arrives one moment that i begin to have problems with the virtual memory (it is near at 100% of capacity), and my laptop begins to do strange things, so at the end I have to reboot.
