### ISSUE TITLE
Sophos AV malware detection

### ISSUE THREAD

**Issue by dellasorte** [henrypp/memreduct#88]
Hi Henry. I'd like to install your memreduct but my Sophos AV detected it as ML/PE-A - Malware / Portable Executable (A) . I saw  this detection previously with metasploit meterpreter stagers in custom executable template. Can you please comment it?

**Comment by dellasorte** [comment]
PUA.Win.Downloader.Aiis-6803892-0

**Comment by henrypp** [comment]
Do you know what is false positive?

https://github.com/henrypp/freeshooter/issues/29
