### ISSUE TITLE
[Suggestion] Reinstate "ReductConfirmation" Config

### ISSUE THREAD

**Issue by hairycactus** [henrypp/memreduct#9]
In **Mem Reduct v 3.1.x** (since 27 Oct 2015), it is no longer possible to click the <code>Clean memory</code> button at the GUI's parent window without triggering the prompt message <code>Do you want to start memory cleaning?" [Yes/No]</code>.

![memreduct-reductconfirm-31oct15a](https://cloud.githubusercontent.com/assets/9943769/10864089/209b54c0-801d-11e5-9420-77716cfc13ae.png)

Also, adding any of the following config keys to <code>memreduct.ini</code> has no effect:
```javascript
[memreduct]
ReductConfirmation=0
ReductConfirm=0
CleanMemoryConfirmation=0
```
On the other hand, in **Mem Reduct v 3.0.436** (01 May 2015), there was a config option allowing user to avoid that prompt message if preferred:
<code>File > Settings > General > General Configuration: Confirm memory cleaning start</code>

![memreduct-reductconfirm-31oct15b](https://cloud.githubusercontent.com/assets/9943769/10864097/56f9ff6c-801d-11e5-998b-ad63d93287b6.png)

And correspondingly in <code>memreduct.ini</code>:
```javascript
[memreduct]
ReductConfirmation=0
```
I had found the above config useful & convenient in the sense that when I bring up the GUI's parent window & click the<code>Clean memory</code> button, it means I *really want* to start memory cleaning. 

Hope that the aforementioned config option can be reinstated. It needs not show up in the GUI's settings. The user can manually edit <code>memreduct.ini</code> sucn that <code>ReductConfirmation=0</code> (or any other key name specified in the <code>readme.txt</code> file).

Thanks !

**Comment by henrypp** [comment]
ok, i reinstate it as soon as posible!

**Comment by hairycactus** [comment]
Thanks. Reinstating <code>ReductConfirmation=0</code> would be helpful, especially since <code>AlwaysOnTop=1</code> continues to remain functional.

There might be users who keep Mem Reduct's GUI on top (or bring it to the desktop from the Taskbar), & utilize the <code>Clean memory</code> button because the keyboard or hotkeys are inaccessible for whatever reason, for instance:-

* Impaired dexterity or physical disability making standard 2-key hotkeys difficult to use
— Mem Reduct requires 2 unique input-keys for the hotkeys setting

* Hardware/ keyboard malfunction

* The recent but apparently resolved bug, where Mem Reduct keeps forgetting the user-customized hotkeys setting.
