### ISSUE TITLE
about Standby List

### ISSUE THREAD

**Issue by Yurie13** [henrypp/memreduct#92]
is it me or Standby List (both of them) are not included/cleaned when auto-clear (above/every) got activated?

PS: it works if i manually "Clean memory"

**Comment by OlimDev** [comment]
This also the problem with the Modified Page list, this actually cleans the RAM more efficiently, and it boost your computer, for some reason it does not getting automatically getting cleaned.

**Comment by OlimDev** [comment]
This app is also did not got update since.

**Comment by henrypp** [comment]
> is it me or Standby List (both of them) are not included/cleaned when auto-clear (above/every) got activated?

It is not cleaned only when autocleanup triggers for speed reason. Manual cleanup did not restrict  Standby list.

I think to add config to opt-out this restriction.
