### ISSUE TITLE
About Memreduct

### ISSUE THREAD

**Issue by Taylor13Swift** [henrypp/memreduct#93]
Memreduct regularly woring on desktop, but it does't clear memory automatically on laptop( i had set it clear automatically)
Besides,sometimes i click to clear,it will close positively and open itself automatically to work
how to deal with???

**Comment by henrypp** [comment]
Mem Reduct does not clean memory without admin rights.

**Comment by DanilMus** [comment]
I won't start Mem Reduct. When I click on the shortcut, it opens, but after 2 seconds it collapses. I don't know what to do.

**Comment by GFOXSH** [comment]
I disable user account control and check the box to skip it in MemReduct and it's work fine for me... My Windows 10 build is 2004.
![fine](https://user-images.githubusercontent.com/15711761/91160185-c243d480-e6d1-11ea-93d5-573d3bb3a399.png)

**Comment by Gildum** [comment]
@GFOXSH 
You don't need to disable your windows user account control, simply check the box "Skip User Account Control prompt warning" in mem reduct's general settings, and then turn off "run as admin" setting of the mem reduct shortcut:
- right click on short cut 
- select properties
- go to compatibility tab
- uncheck "Run this program as an administrator

**Comment by GFOXSH** [comment]
@Gildum not usable for me.
