### ISSUE TITLE
"rapp.hpp" and "routine.hpp"

### ISSUE THREAD

**Issue by theGodBlessedOne** [henrypp/memreduct#97]
There's no "rapp.hpp" and "routine.hpp" in the code!

Where can i get them?

**Comment by YouReTs** [comment]
There's no "rapp.hpp" and "routine.hpp" in the code!

Where can i get them?

**Comment by yi-Xu-0100** [comment]
Use submodule. <https://github.com/henrypp/memreduct/blob/master/.gitmodules>

**Comment by henrypp** [comment]
`git clone --recursive`
