### ISSUE TITLE
Boot with the system

### ISSUE THREAD

**Issue by ceuinifnito** [henrypp/memreduct#98]
![Captura de tela 2021-01-10 041927a](https://user-images.githubusercontent.com/77224252/104117298-f1648680-52fe-11eb-8672-979bb1e22ac1.png)

How are you!

All right?

First of all, I would like to thank you for the program!

Can you help me?

However, I found it difficult to start Men Reduct.

Each time I boot the system, I need to click to clear the memory, as this is not done automatically!

Thankful!

**Comment by henrypp** [comment]
#86

**Comment by ceuinifnito** [comment]
Did not work!

This UAC option is already at a minimum!

What would be the next solution?

Thanks!

**Comment by henrypp** [comment]
> What would be the next solution?

I really don't know, because telepaths in vacations.
