### ISSUE TITLE
Where is my virtual memory actually stored?

### ISSUE THREAD

**Issue by ZergShadow** [henrypp/memreduct#99]
I have 32 gb ram.I have only 20gb free space on hard disk and 4 gb  pagefile. This program says that i have 36gb virtual memory .  Where this 36 gb stored if i only  have 20 gb free space and only 10% of virtual memory is free. Or virtual memory its ram + pagefile so 32 gb stored in ram and 4 gb stored on hard disk? Bcs i always have crashing of explorer seems bcs of luck of ram. I should increase pagefile manually to avoid this ?

**Comment by henrypp** [comment]
![rtfm](https://user-images.githubusercontent.com/3902025/106705357-b693fc80-65e5-11eb-8a39-3921c924a47d.png)
